on:
  - pull_request:
    issues:

jobs:
  chatwork:
    runs-on: ubuntu-latest
    name: send chatwork message
    steps:
      - name: send
        id: send
        uses: yasui-esquare/github-chatwork@v0.2
        with:
          - room: "${{secrets.CHATWORK_ROOM}}"
            token: "${{secrets.CHATWORK_TOKEN}}"
