on:
  pull_request:

jobs:
  chatwork:
    runs-on: ubuntu-latest
    name: send chatwork message
    steps:
      - name: debug
        run: |
          echo "room = ${{ secrets.CHATWORK_ROOM }}"

      - name: send
        uses: yasui-esquare/github-chatwork@main
        with:
          room: ${{ secrets.CHATWORK_ROOM }}
          token: ${{ secrets.CHATWORK_TOKEN }}
