on:
  pull_request_review:

jobs:
  chatwork:
    runs-on: ubuntu-latest
    name: 'send chatwork message'
    steps:
      - name: debug
        run: |
          echo "${{ toJson(github.event.pull_request.user.login) }}"
      - name: send
        uses: yasui-esquare/github-chatwork@main
        with:
          room: ${{ secrets.CHATWORK_ROOM }}
          token: ${{ secrets.CHATWORK_TOKEN }}
          alias: |
            {
              "yasui-esquare": "[To:???]yasui"
            }
          mensions: "[ \"${{ github.event.pull_request.user.login }}\" ]"
          text: "レビュー更新"
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.review.body }}
